sudo: false
language: haskell
ghc: 7.8
install:
- cabal update
- cabal install cabal-install
- cabal --version
- git clone --depth 1 https://github.com/idris-lang/Idris-dev.git vendor/idris
- git clone --depth 1 https://github.com/bamboo/language-cil.git --branch idris-cil --single-branch vendor/language-cil
script:
- cd vendor/language-cil && cabal sandbox init --sandbox ../sandbox && cabal install --only-dependencies -j2 && cabal install
- cd ../..
- cd vendor/idris && cabal sandbox init --sandbox ../sandbox && make && make install
- cd ../..
- cabal sandbox init --sandbox vendor/sandbox
- cabal install --only-dependencies --enable-tests -j2 && cabal configure --enable-tests
- export PATH=$(pwd)/vendor/sandbox/bin:$PATH && cabal build && cabal test --show-details=always --test-options="--color" && cabal check
